# VoicechatMute Configuration
# Compatible with Paper & Folia

settings:
  hooks:
    litebans: true
    advancedban: true
    simplevoicechat: true


messages:
  muted-actionbar: "<red>You are muted in voice chat!</red> <gray>|</gray> <gold>Reason: %reason%</gold>"
  muted-chat: "&cYou are muted in voice chat! &7| &6Reason: %reason%"
